=== KW-M/rov-web/rov-tooling/config-files/rov-config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "LogLevel": {
            "description": "Log level for the python code. One of the following: DEBUG, INFO, WARNING, ERROR, CRITICAL",
            "type": "string"
        },
        "RovName": {
            "description": "Name of the ROV. Must be unique for each ROV. Used to identify the ROV in the web interface.",
            "type": "string"
        },
        "RovControlPassword": {
            "description": "Hashed password for the ROV. Used to encrypt auth tokens. Use the 'hash_password.py' script to generate the hash for your desired password. The raw password is not stored anywhere, the hashed password is used as the key to encrypt the livekit auth tokens",
            "type": "string"
        },
        "AuthStateStorageFilepath": {
            "description": "Path to the file where the auth state is stored. This file is used to store the auth tokens for the ROV. The file is encrypted using the password hash.",
            "type": "string"
        },
        "AuthTokenTimeout": {
            "description": "Time in seconds after which auth tokens will expire. This is the time after which the user will need to enter the password again on the web interface.  Note: this will also be passed to the internal webpage as a query parameter.",
            "type": "integer"
        },
        "PythonWebsocketPort": {
            "description": "Local network port on which the python websocket server will run. This is used to communicate between the python code and the internal webpage. Note: this will also be passed to the internal webpage as a query parameter.",
            "type": "integer"
        },
        "InternalWebpageUrl": {
            "description": "URL of the internal webpage that runs in chromium on the ROV and is not accessible from outside the ROV. It is NOT the piloting webpage used to control/drive the rov.",
            "type": "string"
        },
        "InternalWebpageUrlQueryParams": {
            "description": "Query parameters to be passed to the internal webpage. This is used to pass options and secret keys to the internal webpage.",
            "type": "object",
            "properties": {
                "LivekitCloudUrl": {
                    "description": "URL of the livekit server, eg: https://my-rov.livekit.cloud",
                    "type": "string"
                },
                "LivekitApiKey": {
                    "description": "API key for the livekit server",
                    "type": "string"
                },
                "LivekitSecretKey": {
                    "description": "Secret key for the livekit server",
                    "type": "string"
                },
                "TwitchStreamKey": {
                    "description": "Stream key for the twitch channel, eg: live_123456789_abcdefghijk123456789, set to 'None' to disable streaming",
                    "type": "string"
                }
            },
            "required": [
                "LivekitCloudUrl",
                "LivekitApiKey",
                "LivekitSecretKey"
            ]
        },
        "EnabledSensors": {
            "description": "List of sensors to enable by name. The names must match the name field of a python sensor class in the 'sensors' folder.",
            "type": "array"
        }
    },
    "required": [
        "RovName",
        "RovControlPassword",
        "InternalWebpageUrlQueryParams"
    ]
}

=== KW-M/rov-web/rov-tooling/config-files/rov-config.example.json
{
    "$schema": "./rov-config.schema.json",
    "LogLevel": "INFO",
    "RovName": "== ROV_NAME_NOT_SET ==",
    "RovControlPassword": "== Put ROV Control Password Here ==",
    "AuthStateStorageFilepath": "~/rov-auth-state.json",
    "AuthTokenTimeout": 86400,
    "PythonWebsocketPort": 8765,
    "InternalWebpageUrl": "http://localhost:8080/internal/index.html",
    "InternalWebpageUrlQueryParams": {
        "LivekitCloudUrl": "== Put LiveKit Cloud URL Here ==",
        "LivekitApiKey": "== Put LiveKit API Key Here ==",
        "LivekitSecretKey": "== Put LiveKit Secret Key Here ==",
        "TwitchStreamKey": "== Put Twitch Stream Key Here =="
    },
    "EnabledSensors": [
        "ICM20948_fused_compass",
        "ms5803_pressure_temp"
    ]
}

=== KW-M/rov-web/tooling/rasberry_pi_setup_scripts/new_config_files/rov-config.example.json
{
    "$schema": "./rov-config.schema.json",
    "LogLevel": "DEBUG",
    "RovName": "== ROV_NAME_NOT_SET ==",
    "RovControlPassword": "== Put ROV Control Password Here ==",
    "AuthStateStorageFilepath": "/home/pi/rov-auth-state.json",
    "AuthTokenTimeout": 86400,
    "PythonWebsocketPort": 8765,
    "InternalWebpageUrl": "http://localhost:80/internal/index.html",
    "InternalWebpageUrlQueryParams": {
        "LivekitCloudUrl": "== Put LiveKit Cloud URL Here ==",
        "LivekitApiKey": "== Put LiveKit API Key Here ==",
        "LivekitSecretKey": "== Put LiveKit Secret Key Here ==",
        "TwitchStreamKey": "== Put Twitch Stream Key Here =="
    },
    "EnabledSensors": [
        "ICM20948_fused_compass",
        "ms5803_pressure_temp"
    ]
}
